# Generated by Django 5.2.1 on 2025-06-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_status_created_at_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
